version: '3.8'

services:
  notifyit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:80"
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL:-http://localhost:3000}
      - REACT_APP_AZURE_CLIENT_ID=${REACT_APP_AZURE_CLIENT_ID}
      - REACT_APP_AZURE_TENANT_ID=${REACT_APP_AZURE_TENANT_ID}
      - PORT=${PORT:-3000}
    restart: unless-stopped
